package com.features;

import java.io.File;

import com.converter.xlshtml.ExcelToHtmlConverter;

public class HTMLGenerator
{
    /**
     * @author GaVaRaVa (https://www.linkedin.com/in/gaurav-edekar) First Argument = Path of the Excel Sheet Second
     * Argument = Destination Directory of the Converter
     */
    public static void main(String[] args)
    {

        // The Spreadsheet is created in such a way that it contains the
        // Template Path in the First Column (args[0])
        // args[1] is the destination
        // Default Names of Output File will be TemplateName_01.html and so on
        // if the name of template is TemplateName

        File spreadsheet = new File(args[0]);
        ExcelToHtmlConverter converter = new ExcelToHtmlConverter(spreadsheet, args[1]);
        /*File spreadsheet = new File("G:\\CORBC\\AutoGenerated-Rides\\Ride_37.xls");
        ExcelToHtmlConverter converter = new ExcelToHtmlConverter(spreadsheet,
                "G:\\CORBC\\AutoGenerated-Rides\\"); */

        if (converter.isBlank(args[0]) || converter.isBlank(args[1])) {
            System.err.println("Path of the Excel Sheet OR Destination of output file is not specified");
            System.exit(0);
        }

        System.out.println("Converting spreadsheet ..." + spreadsheet.getName());
        converter.convert();
    }
}
